version: '3.5'

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    restart: always
    networks:
      - default
      - gateway_network

  php:
    image: php:fpm-alpine
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
    restart: always

networks:
  gateway_network:
    external: true
