<?php

namespace App;

class ErrorList {
    const E_TOKEN_EXPIRED = 'E_TOKEN_EXPIRED';
    const E_TOKEN_INVALID = 'E_TOKEN_INVALID';
    const E_UNAUTHORIZED  = 'E_UNAUTHORIZED';

    const E_USER_NOT_FOUND = 'E_USER_NOT_FOUND';
    const E_INVALID_PASSWORD = 'E_INVALID_PASSWORD';
    const E_USER_BLOCKED = 'E_USER_BLOCKED';

    const E_DONT_HAVE_PERMISSION = 'DO_NOT_HAVE_PERMISSION';

    const E_INTERNAL_SERVER_ERROR = 'E_INTERNAL_SERVER_ERROR';
    const E_INVALID_DATA = 'E_INVALID_DATA';
    const E_REQUEST_BODY_INVALID = 'E_REQUEST_BODY_INVALID';
    const E_NOT_FOUND = 'E_NOT_FOUND';
}

