name: CI/CD

on:
  push:
    branches: [ master, dev, ci ]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        run: php -m
      - name: Install packages
        run: composer install --ignore-platform-reqs
      - name: Prepare artifact
        run: zip -qq -r api.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip

  deploy_docs:
    name: Deploy API documentation
  # if: contains( github.ref, 'dev' )
    if: contains( github.ref, 'disable' )
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update OpenAPI documentation file
        uses: up9cloud/action-rsync@v1.3
        env:
          USER: deployer
          HOST: msk-svrm-go.s.dfms.ga
          PORT: 456
          KEY: ${{ secrets.DEPLOY_KEY }}
          SOURCE: docs.json
          TARGET: /srv/inventory/api/docs/docs.json

  deploy_dev:
    name: Deploy to dev server
    if: contains( github.ref, 'dev' )
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: api
      - name: Extract files from archive
        run: |
          unzip -qq api.zip
          rm api.zip
      - name: Deploy to development server
        uses: up9cloud/action-rsync@v1.3
        env:
          ARGS: -avz --delete --exclude=.git --exclude=.github --exclude=.env.local
          USER: deployer
          HOST: msk-svrm-go.s.dfms.ga
          PORT: 456
          KEY: ${{ secrets.DEPLOY_KEY }}
          TARGET: /srv/inventory/api/stage

  deploy_production:
    name: Deploy to production server
    if: contains( github.ref, 'master' )
    needs: [ setup ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: api
      - name: Extract files from archive
        run: |
          unzip -qq api.zip
          rm api.zip
      - name: Deploy to production server
        uses: up9cloud/action-rsync@v1.3
        env:
          ARGS: -avz --delete --exclude=.git --exclude=.github --exclude=.env.local
          USER: deployer
          HOST: msk-svrm-go.s.dfms.ga
          PORT: 456
          KEY: ${{ secrets.DEPLOY_KEY }}
          TARGET: /srv/inventory/api/master
  
